- build.sbt
- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/OrderEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/PetEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/DoobieOrderRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/DoobiePetRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/PetRepositoryInMemoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/OrderService.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/PetService.scala
- src/main/scala/io/github/pauljamescleary/petstore/validation/PetValidationTaskInterpreter.scala
Also standardized on cats-effect for IO
> Updated to http4s 0.18.0-M1

- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/OrderService.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/PetService.scala
- src/main/scala/io/github/pauljamescleary/petstore/validation/PetValidationInterpreter.scala
There was no need to have implicits for the class variables in this example.  Removing them as they don't add any value here.
> Removed things that need not be implicits

- .scalafmt.conf
- project/build.properties
- project/plugins.sbt
- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/JodaDateTime.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/OrderEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/PetEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/DoobieOrderRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/DoobiePetRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/OrderRepositoryInMemoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/PetRepositoryInMemoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/PetService.scala
- src/main/scala/io/github/pauljamescleary/petstore/validation/PetValidationInterpreter.scala
- src/test/scala/io/github/pauljamescleary/petstore/Arbitraries.scala
> Updated to sbt 1.0

- functional_test/live_tests/pets_test.py
- functional_test/pet_store_client.py
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/PetEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/DoobiePetRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/PetRepositoryAlgebra.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/PetRepositoryInMemoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/PetService.scala
This pull request attempts to achieve the following:
The unit tests haven't been updated to reflect this new endpoint functionality.
> Implemented Find By Tags endpoint.

- build.sbt
- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/OrderEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/PetEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/PetService.scala
There were some strange things with the json handling in the
latest Http4s where I needed to add a decoder as well as
needed to have an implicit Effect in scope for F.
> Updating dependencies to be the latest

- functional_test/live_tests/orders_test.py
- functional_test/pet_store_client.py
- project/build.properties
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/OrderEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/PetEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/repository/DoobieOrderRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/OrderService.scala
- src/main/scala/io/github/pauljamescleary/petstore/validation/PetValidationAlgebra.scala
- src/main/scala/io/github/pauljamescleary/petstore/validation/ValidationError.scala
Added get order by id endpoint
Updated paths to use path params instead of query params when addressing entities by id
> Add get order

- src/main/scala/io/github/pauljamescleary/petstore/endpoint/OrderEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/PetEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/OrderService.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/PetService.scala
- src/main/scala/io/github/pauljamescleary/petstore/validation/PetValidationAlgebra.scala
- src/main/scala/io/github/pauljamescleary/petstore/validation/PetValidationInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/validation/ValidationError.scala
Returning an Either with ValidationError forces the caller
to handle all possible types of ValidationError even if they
are not valid for the specific function call.
Instead of a general ValidationError, return a specific validation
error for the function.
> Cleanup errors

- functional_test/live_tests/orders_test.py
- functional_test/pet_store_client.py
- src/main/scala/io/github/pauljamescleary/petstore/endpoint/OrderEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/service/OrderService.scala
> Adding delete order endpoint

- build.sbt
- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
- src/main/scala/io/github/pauljamescleary/petstore/config/DatabaseConfig.scala
Had to clean up some deprecated items, but this went well.
> Updated all dependencies to latest

- build.sbt
> Update to cats 1.0.1!

- functional_test/live_tests/users_test.py
- functional_test/pet_store_client.py
- src/main/scala/io/github/pauljamescleary/petstore/domain/users/UserRepositoryAlgebra.scala
- src/main/scala/io/github/pauljamescleary/petstore/domain/users/UserService.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/DoobieUserRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/inmemory/UserRepositoryInMemoryInterpreter.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala
This closes #19. Current implementation deletes user from db.
> delete user by username

- README.md
> Add badges for passing build and gitter room

- build.sbt
> Updated scalac options to make repl experience work

- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/DoobiePetRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/DoobieUserRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/Pagination.scala
Just renamed it so that it was clearly related to SQL
> pagination was confusing as it collides with endpoint pagination

- build.sbt
- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
http4s 0.18.0
circe 0.9.1
doobie 0.15.0-RC1
> Updating dependencies

- build.sbt
- project/plugins.sbt
- src/main/tut/index.md
Starting on documentation site.  Using tut + microsites + gh-pages.
Did nothing as far as documentation goes so far.  Just want to have the doc generation lined up so I can just start writing docs.
The site is up at the very least.  Next I plan on putting together some documentation.  The documentation is geared toward OO people new to Scala.
Check it ... https://pauljamescleary.github.io/scala-pet-store/
> Bootstrapping documentation

- functional_test/live_tests/pets_test.py
- functional_test/live_tests/users_test.py
- functional_test/pet_store_client.py
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/Pagination.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/PetEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpoints.scala
pageable routes without any query parameters should return response with default offset and page size
> make PageSizeMatcher and OffsetMatcher optional

- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
Thanks to @rossabaker for chat help in understanding:
https://gitter.im/http4s/http4s?at=5c25581d5064a51f8386d93f
* We were using IO.pure inappropriately, see this comment:
https://github.com/typelevel/cats-effect/blob/v1.0.0/core/shared/src/main/scala/cats/effect/IO.scala#L988
* See http4s docs for discussion about resource/stream:
https://http4s.org/v0.20/service/#running-your-service-as-an-app
> Revise server creation to use http4s's resource instead of stream

- README.md
> Fix travis links

- README.md
- build.sbt
- src/main/scala/io/github/pauljamescleary/petstore/config/PetStoreConfig.scala
- src/main/scala/io/github/pauljamescleary/petstore/config/package.scala
> Remove pureconfig in favor of circe-config

- AUTHORS.md
As proposed kindly by @pauljamescleary
> added Kailuo Wang

- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
- src/main/scala/io/github/pauljamescleary/petstore/config/PetStoreConfig.scala
- src/main/scala/io/github/pauljamescleary/petstore/config/package.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/package.scala
Minor simplification for config loading given updates to circe-config in 0.6.1
> Refactor for circe-config updates

- src/main/resources/reference.conf
- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
- src/main/scala/io/github/pauljamescleary/petstore/config/DatabaseConfig.scala
- src/main/scala/io/github/pauljamescleary/petstore/config/package.scala
Don't know why but it seems to solve #149.
> Use different thread pool for connections in dbTransactor.

- .travis.yml
- build.sh
- functional_test/bootstrap.sh
- functional_test/live_tests/conftest.py
- functional_test/pet_store_client.py
- functional_test/requirements.txt
- functional_test/run.py
This went smoothly, with just a few suggestions from 2to3
> Upgrade to python3

- build.sbt
- src/main/resources/reference.conf
We were not exposing any ports, making the docker image unsuable.
Added exposing docker ports.
> Fix docker build ports

- .travis.yml
- project/build.properties
Also upgrades to sbt 1.3.0-RC1 for coursier
> Add caching ability to travis for faster dependency resolution

- README.md
> Change Python version to 3 in README

- build.sbt
- project/plugins.sbt
This really makes it easier to manage those scalacoptions per scala version.
> Add tpolecat scalac options plugin

- .gitignore
- .scalafmt.conf
- project/project/metals.sbt
- project/project/project/metals.sbt
- src/main/scala/io/github/pauljamescleary/petstore/config/DatabaseConfig.scala
- src/main/scala/io/github/pauljamescleary/petstore/domain/authentication/Auth.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/OrderEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/PetEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpoints.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/DoobieAuthRepositoryInterpreter.scala
- src/test/scala/io/github/pauljamescleary/petstore/Arbitraries.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/LoginTest.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/OrderEndpointsSpec.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/PetEndpointsSpec.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala
scala steward updates have been failing because we have to reformat the files so travis passes.
Updated to latest scalafmt and ran a scalafmtAll
> Fixes for scala format

- .github/workflows/ci.yml
- .mergify.yml
Roll back version update, which I pushed to master by accident.
> Roll back to 2.13.2

- .github/workflows/ci.yml
- .mergify.yml
- build.sbt
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/inmemory/OrderRepositoryInMemoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/inmemory/PetRepositoryInMemoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/inmemory/UserRepositoryInMemoryInterpreter.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/OrderEndpointsSpec.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/PetEndpointsSpec.scala
- src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala
Few new warnings, about auto-application with `()`.
> Upgrade scala 2.13

- build.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/io/github/pauljamescleary/petstore/Server.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/DoobieAuthRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/DoobieOrderRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/DoobiePetRepositoryInterpreter.scala
- src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/doobie/DoobieUserRepositoryInterpreter.scala
Closed all of the scala steward requests and rolled these by hand.  A few required tiny code changes.  This will bring the project current (except for scala 3) as of May 2021
> Updating dependencies as of 05 2021
